[functions]
    # Directory with serverless functions, including background functions,
    # to deploy. This is relative to the base directory if one has been set, 
    # or the root directory if a base hasn’t been set.
    directory = "lambdas/"
[template.environment]
    MONGO_URI = "Your Mongo Cluster URL"
    MONGO_DB_NAME = "Your Mongo Database Name"
    MONGO_USER = "Your Mongo User Name"
    MONGO_PASS = "Your Mongo User Password"
